### ISSUE TITLE
this.baseCable.close is not a function

### ISSUE THREAD

**Issue by jaco-terbraak** [nolancaster/angular2-actioncable#3]
This happens when calling Cable::disconnect(). The Cable connection was working fine beforehand.

It started happening when upgrading from angular2-actioncable 1.1.5 to 1.2.0.
I'm using actioncable 5.2.0 in both cases.

I suspect this commit breaks it: https://github.com/nolancaster/angular2-actioncable/commit/6a0485e0a860e3fb9dc54b2e51988018fd72c4a1#diff-6c7420681cfd43be54badf5663c934e2

**Comment by nolancaster** [comment]
Yeah, I got my wires crossed when looking at the actioncable code. Should be fixed in the 1.2.1 version I just published.

**Comment by jaco-terbraak** [comment]
Thanks!
